[program:rendee-web]
process_name=%(program_name)s
command=php /home/jervi/projects/rendee-server/artisan serve --host=0.0.0.0 --port=18040
autostart=true
autorestart=true
user=jervi
numprocs=1
redirect_stderr=true
stdout_logfile=/home/jervi/projects/rendee-server/storage/logs/web.log
