import type {
  User,
  Patient,
  Professional,
  ProfessionalSchedule,
  ProfessionalService,
  Center,
  CenterWorkingHours,
  CenterService,
  Booking,
  Notification,
  Profession,
  Speciality,
} from './types';

// ─── Catalog Data ────────────────────────────────────────────────────────────

export const mockProfessions: Profession[] = [
  { code: 'doctor', en: 'Doctor', fr: 'Médecin', ar: 'طبيب', hex: '#3B82F6' },
  { code: 'dentist', en: 'Dentist', fr: 'Dentiste', ar: 'طبيب أسنان', hex: '#8B5CF6' },
  { code: 'physiotherapist', en: 'Physiotherapist', fr: 'Kinésithérapeute', ar: 'أخصائي علاج طبيعي', hex: '#10B981' },
];

export const mockSpecialities: Speciality[] = [
  { id: 1, code: 'cardiology', en: 'Cardiology', fr: 'Cardiologie', ar: 'أمراض القلب' },
  { id: 2, code: 'dermatology', en: 'Dermatology', fr: 'Dermatologie', ar: 'الأمراض الجلدية' },
  { id: 3, code: 'orthodontics', en: 'Orthodontics', fr: 'Orthodontie', ar: 'تقويم الأسنان' },
  { id: 4, code: 'general', en: 'General Practice', fr: 'Médecine Générale', ar: 'طب عام' },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 1,
    user_role_code: 'professional',
    name: 'drbenmoussa',
    email: 'dr.benmoussa@rendee.dz',
    email_verified_at: '2025-01-15T10:00:00Z',
    full_name: 'Dr. Karim Benmoussa',
    image_url: null,
    phone_number: '+213 555 123 456',
    profile_complete: true,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-06-01T14:30:00Z',
  },
  {
    id: 2,
    user_role_code: 'professional',
    name: 'drferhati',
    email: 'dr.ferhati@rendee.dz',
    email_verified_at: '2025-02-20T09:00:00Z',
    full_name: 'Dr. Amina Ferhati',
    image_url: null,
    phone_number: '+213 555 234 567',
    profile_complete: true,
    created_at: '2025-02-18T10:00:00Z',
    updated_at: '2025-06-10T11:00:00Z',
  },
  {
    id: 3,
    user_role_code: 'professional',
    name: 'drkhaldi',
    email: 'dr.khaldi@rendee.dz',
    email_verified_at: '2025-03-05T08:30:00Z',
    full_name: 'Dr. Youcef Khaldi',
    image_url: null,
    phone_number: '+213 555 345 678',
    profile_complete: true,
    created_at: '2025-03-01T07:00:00Z',
    updated_at: '2025-06-15T09:00:00Z',
  },
  {
    id: 4,
    user_role_code: 'patient',
    name: 'sarahboudiaf',
    email: 'sarah.boudiaf@gmail.com',
    email_verified_at: '2025-04-10T12:00:00Z',
    full_name: 'Sarah Boudiaf',
    image_url: null,
    phone_number: '+213 555 456 789',
    profile_complete: true,
    created_at: '2025-04-08T10:00:00Z',
    updated_at: '2025-06-20T16:00:00Z',
  },
  {
    id: 5,
    user_role_code: 'patient',
    name: 'mohamedzerrouki',
    email: 'mohamed.zerrouki@gmail.com',
    email_verified_at: '2025-05-01T14:00:00Z',
    full_name: 'Mohamed Zerrouki',
    image_url: null,
    phone_number: '+213 555 567 890',
    profile_complete: false,
    created_at: '2025-05-01T13:00:00Z',
    updated_at: '2025-06-25T10:00:00Z',
  },
  {
    id: 6,
    user_role_code: 'center',
    name: 'cliniqueelamel',
    email: 'contact@clinique-elamel.dz',
    email_verified_at: '2025-01-20T09:00:00Z',
    full_name: 'Clinique El Amel',
    image_url: null,
    phone_number: '+213 21 456 789',
    profile_complete: true,
    created_at: '2025-01-18T08:00:00Z',
    updated_at: '2025-07-01T10:00:00Z',
  },
  {
    id: 7,
    user_role_code: 'center',
    name: 'centresoins',
    email: 'info@centre-soins-alger.dz',
    email_verified_at: '2025-02-10T10:00:00Z',
    full_name: 'Centre de Soins Alger',
    image_url: null,
    phone_number: '+213 21 567 890',
    profile_complete: true,
    created_at: '2025-02-08T09:00:00Z',
    updated_at: '2025-07-05T12:00:00Z',
  },
];

// ─── Patients ────────────────────────────────────────────────────────────────

export const mockPatients: Patient[] = [
  {
    id: 1,
    user_id: 4,
    date_of_birth: '1992-08-15',
    gender: 'female',
    address: '12 Rue Didouche Mourad',
    city: 'Algiers',
    medical_notes: 'No known allergies',
    created_at: '2025-04-08T10:00:00Z',
    updated_at: '2025-06-20T16:00:00Z',
    user: mockUsers[3],
  },
  {
    id: 2,
    user_id: 5,
    date_of_birth: '1988-03-22',
    gender: 'male',
    address: '45 Boulevard Krim Belkacem',
    city: 'Oran',
    medical_notes: 'Diabetic — Type 2',
    created_at: '2025-05-01T13:00:00Z',
    updated_at: '2025-06-25T10:00:00Z',
    user: mockUsers[4],
  },
];

// ─── Professionals ───────────────────────────────────────────────────────────

export const mockProfessionals: Professional[] = [
  {
    id: 1,
    user_id: 1,
    profession_code: 'doctor',
    professional_speciality_code: 'cardiology',
    wilaya_code: '16',
    license_number: 'ALG-MED-2018-4521',
    years_experience: '12',
    phone_public: '+213 555 123 456',
    bio: 'Cardiologue spécialisé dans les maladies cardiovasculaires. Diplômé de la faculté de médecine d\'Alger.',
    address: '32 Rue Larbi Ben M\'hidi',
    city: 'Algiers',
    latitude: 36.7538,
    longitude: 3.0588,
    is_available: true,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-06-01T14:30:00Z',
    user: mockUsers[0],
    speciality: mockSpecialities[0],
    profession: mockProfessions[0],
  },
  {
    id: 2,
    user_id: 2,
    profession_code: 'dentist',
    professional_speciality_code: 'orthodontics',
    wilaya_code: '31',
    license_number: 'ALG-DEN-2020-1234',
    years_experience: '8',
    phone_public: '+213 555 234 567',
    bio: 'Orthodontiste passionnée par les soins dentaires esthétiques et fonctionnels.',
    address: '18 Avenue de l\'ANP',
    city: 'Oran',
    latitude: 35.6969,
    longitude: -0.6331,
    is_available: true,
    created_at: '2025-02-18T10:00:00Z',
    updated_at: '2025-06-10T11:00:00Z',
    user: mockUsers[1],
    speciality: mockSpecialities[2],
    profession: mockProfessions[1],
  },
  {
    id: 3,
    user_id: 3,
    profession_code: 'doctor',
    professional_speciality_code: 'general',
    wilaya_code: '25',
    license_number: 'ALG-MED-2015-7890',
    years_experience: '15',
    phone_public: '+213 555 345 678',
    bio: 'Médecin généraliste avec une approche holistique de la santé.',
    address: '5 Rue Abane Ramdane',
    city: 'Constantine',
    latitude: 36.365,
    longitude: 6.6147,
    is_available: false,
    created_at: '2025-03-01T07:00:00Z',
    updated_at: '2025-06-15T09:00:00Z',
    user: mockUsers[2],
    speciality: mockSpecialities[3],
    profession: mockProfessions[0],
  },
];

// ─── Schedules ───────────────────────────────────────────────────────────────

export const mockSchedules: ProfessionalSchedule[] = [
  { id: 1, professional_id: 1, day_of_week: 0, start_time: '08:00', end_time: '12:00', is_active: true },
  { id: 2, professional_id: 1, day_of_week: 0, start_time: '14:00', end_time: '17:00', is_active: true },
  { id: 3, professional_id: 1, day_of_week: 1, start_time: '08:00', end_time: '12:00', is_active: true },
  { id: 4, professional_id: 1, day_of_week: 2, start_time: '08:00', end_time: '16:00', is_active: true },
  { id: 5, professional_id: 1, day_of_week: 3, start_time: '09:00', end_time: '13:00', is_active: true },
  { id: 6, professional_id: 1, day_of_week: 4, start_time: '08:00', end_time: '12:00', is_active: true },
  { id: 7, professional_id: 1, day_of_week: 5, start_time: null, end_time: null, is_active: false },
  { id: 8, professional_id: 1, day_of_week: 6, start_time: null, end_time: null, is_active: false },
];

// ─── Professional Services ───────────────────────────────────────────────────

export const mockProfessionalServices: ProfessionalService[] = [
  { id: 1, professional_id: 1, service_catalog_code: 'consultation', price: 3000, duration_minutes: 30 },
  { id: 2, professional_id: 1, service_catalog_code: 'ecg', price: 5000, duration_minutes: 45 },
  { id: 3, professional_id: 2, service_catalog_code: 'dental_checkup', price: 2500, duration_minutes: 20 },
  { id: 4, professional_id: 2, service_catalog_code: 'orthodontic_fitting', price: 15000, duration_minutes: 60 },
];

// ─── Centers ─────────────────────────────────────────────────────────────────

export const mockCenters: Center[] = [
  {
    id: 1,
    user_id: 6,
    name: 'Clinique El Amel',
    center_catalog_code: 'clinic',
    wilaya_code: '16',
    license_number: 'CLN-ALG-2019-001',
    phone_public: '+213 21 456 789',
    description: 'Clinique multidisciplinaire offrant des soins de qualité au cœur d\'Alger.',
    address: '100 Route de l\'Aéroport',
    city: 'Algiers',
    latitude: 36.7194,
    longitude: 3.1796,
    emergency_24_7: true,
    is_active: true,
    created_at: '2025-01-18T08:00:00Z',
    updated_at: '2025-07-01T10:00:00Z',
    user: mockUsers[5],
  },
  {
    id: 2,
    user_id: 7,
    name: 'Centre de Soins Alger',
    center_catalog_code: 'health_center',
    wilaya_code: '16',
    license_number: 'CSA-ALG-2020-042',
    phone_public: '+213 21 567 890',
    description: 'Centre de soins spécialisé dans la médecine préventive et le suivi des maladies chroniques.',
    address: '22 Rue Mohamed Belouizdad',
    city: 'Algiers',
    latitude: 36.7486,
    longitude: 3.0576,
    emergency_24_7: false,
    is_active: true,
    created_at: '2025-02-08T09:00:00Z',
    updated_at: '2025-07-05T12:00:00Z',
    user: mockUsers[6],
  },
];

// ─── Center Working Hours ────────────────────────────────────────────────────

export const mockCenterWorkingHours: CenterWorkingHours[] = [
  { id: 1, center_id: 1, slot_date: '2025-07-28', start_time: '08:00', end_time: '12:00', is_available: true },
  { id: 2, center_id: 1, slot_date: '2025-07-28', start_time: '14:00', end_time: '18:00', is_available: true },
  { id: 3, center_id: 1, slot_date: '2025-07-29', start_time: '08:00', end_time: '12:00', is_available: true },
  { id: 4, center_id: 1, slot_date: '2025-07-29', start_time: '14:00', end_time: '18:00', is_available: false },
  { id: 5, center_id: 2, slot_date: '2025-07-28', start_time: '09:00', end_time: '16:00', is_available: true },
];

// ─── Center Services ─────────────────────────────────────────────────────────

export const mockCenterServices: CenterService[] = [
  { id: 1, center_id: 1, service_catalog_code: 'general_consultation', description: 'Consultation médicale générale', price: 2000, duration_minutes: 20, is_active: true },
  { id: 2, center_id: 1, service_catalog_code: 'blood_test', description: 'Analyses sanguines complètes', price: 3500, duration_minutes: 15, is_active: true },
  { id: 3, center_id: 2, service_catalog_code: 'physiotherapy_session', description: 'Séance de kinésithérapie', price: 4000, duration_minutes: 45, is_active: true },
];

// ─── Bookings ────────────────────────────────────────────────────────────────

export const mockBookings: Booking[] = [
  {
    id: 1,
    reference: 'RND-2025-0001',
    patient_id: 1,
    bookable_type: 'professional',
    bookable_id: 1,
    service_type: 'professional_service',
    service_id: 1,
    schedule_type: 'professional_schedule',
    schedule_id: 1,
    patient_name: 'Sarah Boudiaf',
    patient_phone: '+213 555 456 789',
    booking_date: '2025-07-28',
    booking_time: '09:00',
    status_code: 'confirmed',
    is_center: false,
    proposed_date: null,
    proposed_time: null,
    has_pending_proposal: false,
    notes: 'Suivi cardiologique trimestriel',
    created_at: '2025-07-20T10:00:00Z',
    updated_at: '2025-07-21T08:00:00Z',
  },
  {
    id: 2,
    reference: 'RND-2025-0002',
    patient_id: 2,
    bookable_type: 'professional',
    bookable_id: 2,
    service_type: 'professional_service',
    service_id: 3,
    schedule_type: null,
    schedule_id: null,
    patient_name: 'Mohamed Zerrouki',
    patient_phone: '+213 555 567 890',
    booking_date: '2025-07-29',
    booking_time: '10:30',
    status_code: 'pending',
    is_center: false,
    proposed_date: null,
    proposed_time: null,
    has_pending_proposal: false,
    notes: null,
    created_at: '2025-07-22T14:00:00Z',
    updated_at: '2025-07-22T14:00:00Z',
  },
  {
    id: 3,
    reference: 'RND-2025-0003',
    patient_id: 1,
    bookable_type: 'center',
    bookable_id: 1,
    service_type: 'center_service',
    service_id: 2,
    schedule_type: null,
    schedule_id: null,
    patient_name: 'Sarah Boudiaf',
    patient_phone: '+213 555 456 789',
    booking_date: '2025-07-30',
    booking_time: '14:00',
    status_code: 'pending',
    is_center: true,
    proposed_date: '2025-07-31',
    proposed_time: '15:00',
    has_pending_proposal: true,
    notes: 'Analyses de routine',
    created_at: '2025-07-23T09:00:00Z',
    updated_at: '2025-07-23T16:00:00Z',
  },
  {
    id: 4,
    reference: 'RND-2025-0004',
    patient_id: 2,
    bookable_type: 'professional',
    bookable_id: 1,
    service_type: 'professional_service',
    service_id: 2,
    schedule_type: 'professional_schedule',
    schedule_id: 4,
    patient_name: 'Mohamed Zerrouki',
    patient_phone: '+213 555 567 890',
    booking_date: '2025-07-15',
    booking_time: '11:00',
    status_code: 'completed',
    is_center: false,
    proposed_date: null,
    proposed_time: null,
    has_pending_proposal: false,
    notes: 'ECG de contrôle — résultats normaux',
    created_at: '2025-07-10T08:00:00Z',
    updated_at: '2025-07-15T12:00:00Z',
  },
  {
    id: 5,
    reference: 'RND-2025-0005',
    patient_id: 1,
    bookable_type: 'professional',
    bookable_id: 3,
    service_type: null,
    service_id: null,
    schedule_type: null,
    schedule_id: null,
    patient_name: 'Sarah Boudiaf',
    patient_phone: '+213 555 456 789',
    booking_date: '2025-07-20',
    booking_time: '09:30',
    status_code: 'cancelled',
    is_center: false,
    proposed_date: null,
    proposed_time: null,
    has_pending_proposal: false,
    notes: 'Annulé par le patient',
    created_at: '2025-07-18T11:00:00Z',
    updated_at: '2025-07-19T08:00:00Z',
  },
];

// ─── Notifications ───────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: 1,
    user_id: 4,
    title: 'Rendez-vous confirmé',
    body: 'Votre rendez-vous avec Dr. Benmoussa le 28/07 à 09:00 a été confirmé.',
    type: 'booking_confirmed',
    data: { booking_id: 1 },
    is_read: false,
    created_at: '2025-07-21T08:00:00Z',
    updated_at: '2025-07-21T08:00:00Z',
  },
  {
    id: 2,
    user_id: 4,
    title: 'Proposition de nouveau créneau',
    body: 'Clinique El Amel vous propose un nouveau créneau le 31/07 à 15:00.',
    type: 'booking_proposal',
    data: { booking_id: 3 },
    is_read: false,
    created_at: '2025-07-23T16:00:00Z',
    updated_at: '2025-07-23T16:00:00Z',
  },
  {
    id: 3,
    user_id: 1,
    title: 'Nouveau rendez-vous',
    body: 'Mohamed Zerrouki a réservé un ECG pour le 15/07 à 11:00.',
    type: 'new_booking',
    data: { booking_id: 4 },
    is_read: true,
    created_at: '2025-07-10T08:00:00Z',
    updated_at: '2025-07-10T09:00:00Z',
  },
  {
    id: 4,
    user_id: 5,
    title: 'Rappel de rendez-vous',
    body: 'Rappel : vous avez un rendez-vous demain avec Dr. Ferhati à 10:30.',
    type: 'booking_reminder',
    data: { booking_id: 2 },
    is_read: false,
    created_at: '2025-07-28T18:00:00Z',
    updated_at: '2025-07-28T18:00:00Z',
  },
];
